### ISSUE TITLE
现在  实现什么功能了    加油 

### ISSUE THREAD

**Issue by sakuratyan** [YuleYu/HS_Bot#1]
心有余 力不足

**Comment by YuleYu** [comment]
卡没写完，还无法跑起来……
现在写卡的速度赶不上其更新的速度，每次新的拓展包都意味着大量的修改与超过一百张新卡的补充。
主要是版本更新带来的问题，比如加基森中卡扎库斯的药水特效、安戈洛的“进化”，etc。细节考虑都比较花时间。
随着学业繁忙，有点想弃坑😵

**Comment by sakuratyan** [comment]
接近小白吧   会一点c和python   不过对炉石脚本有兴趣  有哪些力所能及的事情可以做呢

**Comment by YuleYu** [comment]
可以试着来帮我写卡2333
用邮箱联系我吧，这个 issue 不算问题我先关了……
