### ISSUE TITLE
你好 偶然看到的 现在HB已经免费了呀 有破解 可以去hb贴吧看看 就叫炉石兄弟吧

### ISSUE THREAD

**Issue by miku-Sakura** [YuleYu/HS_Bot#3]
但是好像有点问题，要自己添加新卡之类，不过他的ai还是很不错的，据说还是有人挂上传说，支持你，希望您能弄一个新的bot

**Comment by YuleYu** [comment]
居然是这样，看来是我 out 了😂……之前忙着毕设也没怎么上心这个项目，现在有些架构已经忘了……有空去贴吧看看，试试反编译😝，学习一下 HB 。
anyway，谢谢啦！

ps: 你也还在上学吗，现在升学之后学业繁重，感觉自己鼓捣的时间与精力真的有限……

miku-Sakura <notifications@github.com> 于2018年10月6日周六 下午10:43写道：

**Comment by miku-Sakura** [comment]
哈哈，没事，可惜我是个小白不会弄，我自己在用hearthranger，ai很蠢，只能打打金币，hb虽然停更了，但是添加了新卡ai还是能上低保也有传说的，我懒得捣鼓，就到处找了找有没有新的bot，羡慕你们这种会弄的0.0不过这东西肯定很难，不然hearthranger怎么赚了那么多钱ai还是一个屎，silverfish也不更新了

**Comment by miku-Sakura** [comment]
> 居然是这样，看来是我 out 了😂……之前忙着毕设也没怎么上心这个项目，现在有些架构已经忘了……有空去贴吧看看，试试反编译😝，学习一下 HB 。 anyway，谢谢啦！ ps: 你也还在上学吗，现在升学之后学业繁重，感觉自己鼓捣的时间与精力真的有限…… miku-Sakura <notifications@github.com> 于2018年10月6日周六 下午10:43写道：
> […](#)



> 居然是这样，看来是我 out 了😂……之前忙着毕设也没怎么上心这个项目，现在有些架构已经忘了……有空去贴吧看看，试试反编译😝，学习一下 HB 。 anyway，谢谢啦！ ps: 你也还在上学吗，现在升学之后学业繁重，感觉自己鼓捣的时间与精力真的有限…… miku-Sakura <notifications@github.com> 于2018年10月6日周六 下午10:43写道：
> […](#)

哈哈，没事，可惜我是个小白不会弄，我自己在用hearthranger，ai很蠢，只能打打金币，hb虽然停更了，但是添加了新卡ai还是能上低保也有传说的，我懒得捣鼓，就到处找了找有没有新的bot，羡慕你们这种会弄的0.0不过这东西肯定很难，不然hearthranger怎么赚了那么多钱ai还是一个屎，silverfish也不更新了
